//
// Body.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Body: JSONEncodable {
    /** List name. */
    public var list: String?
    /** Item count. */
    public var count: Int32?
    /** Page number. */
    public var page: Int32?
    /** Optional enumerator. You can assign the mode of implementation of where criterions by using AND and OR types under whereType parameter. */
    public var whereType: String?
    public var _where: [WhereItem]?
    public var order: ListOrder?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["list"] = self.list
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["page"] = self.page?.encodeToJSON()
        nillableDictionary["whereType"] = self.whereType
        nillableDictionary["where"] = self._where?.encodeToJSON()
        nillableDictionary["order"] = self.order?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
